Repository Kyutech-C3/ToyBox_front_replace, pull requests merged in 2023-12, with the labels that each got.

#123 Chore/change archtecture #117
  _templates/generator/model/component.ejs.t
  _templates/generator/model/container.ejs.t
  _templates/generator/model/empty.ejs.t
  _templates/generator/model/error.ejs.t
  _templates/generator/model/hooks.ejs.t
  _templates/generator/model/index.ejs.t
  _templates/generator/model/loading.ejs.t
  _templates/generator/model/main.ejs.t
  _templates/generator/model/prompt.js
  _templates/generator/model/stories.ejs.t
  _templates/generator/model/test.ejs.t
  aspida.config.js
  cspell.config.json
  package.json
  pnpm-lock.yaml
  src/api/$api.ts
  src/api/@types/index.ts
  src/api/api/$api.ts
  src/api/api/v1/$api.ts
  src/api/api/v1/blogs/$api.ts
  src/api/api/v1/blogs/_blog_id@string/index.ts
  src/api/api/v1/blogs/assets/$api.ts
  src/api/api/v1/blogs/assets/index.ts
  src/api/api/v1/blogs/index.ts
  src/api/api/v1/users/@me/avatar/index.ts
  src/api/api/v1/users/@me/blogs/index.ts
  src/api/api/v2/$api.ts
  src/api/api/v2/works/$api.ts
  src/api/api/v2/works/index.ts
  src/components/model/Work/components/index.ts
  src/components/model/Work/index.ts
  src/components/model/Work/repository/get/getWorks.ts
  src/components/model/Work/repository/get/index.ts
  src/components/model/Work/repository/get/type.ts
  src/components/model/Work/repository/index.ts
  src/components/model/Work/repository/repository.ts
  src/components/model/Work/types/index.ts
  src/components/model/Work/usecase/converter/index.ts
  src/components/model/Work/usecase/converter/work.ts
  src/components/model/Work/usecase/get/getWorks/genKey.ts
  src/components/model/Work/usecase/get/getWorks/getWorks.ts
  src/components/model/Work/usecase/get/getWorks/index.ts
  src/components/model/Work/usecase/get/index.ts
  src/components/model/Work/usecase/index.ts
  src/components/model/Work/usecase/usecase.ts
  src/components/model/Work/utils/index.ts
  src/constants/baseUrl/baseUrl.ts
  src/constants/baseUrl/index.ts
  src/hooks/useApiClient.ts
  src/libs/fetch/index.ts
Labels: priority high

#131 fix: change package manager pnpm to bun
  .github/actions/bun/action.yml
  .github/actions/pnpm/action.yml
  .github/workflows/chromatic_deploy.yml
  .github/workflows/ci.yml
  bun.lockb
  pnpm-lock.yaml
Labels: priority high

#129 feat: add input ui
  cspell.config.json
  src/components/ui/Input/index.stories.tsx
  src/components/ui/Input/index.test.tsx
  src/components/ui/Input/index.tsx
Labels: priority medium

#133 chore: husky command pnpm to bun
  .husky/commit-msg
  .husky/post-merge
  .husky/pre-push
  package.json
Labels: priority medium

#138 chore: husky command pnpm to bun (pre-commit)
  .husky/pre-commit
Labels: priority medium

#137 chore: add jest --watch script
  package.json
Labels: priority low

#135 feat: add card Components
  src/components/ui/Card/index.stories.tsx
  src/components/ui/Card/index.test.tsx
  src/components/ui/Card/index.tsx
Labels: priority medium

#147 feat: add model presentation generation
  _templates/generator/model/container/component.ejs.t
  _templates/generator/model/container/container.ejs.t
  _templates/generator/model/container/empty.ejs.t
  _templates/generator/model/container/error.ejs.t
  _templates/generator/model/container/hooks.ejs.t
  _templates/generator/model/container/index.ejs.t
  _templates/generator/model/container/loading.ejs.t
  _templates/generator/model/container/main.ejs.t
  _templates/generator/model/container/prompt.js
  _templates/generator/model/container/stories.ejs.t
  _templates/generator/model/container/test.ejs.t
  _templates/generator/model/presentation/index.ejs.t
  _templates/generator/model/presentation/main.ejs.t
  _templates/generator/model/presentation/prompt.js
  _templates/generator/model/presentation/skeleton.t
  _templates/generator/model/presentation/stories.ejs.t
  _templates/generator/model/presentation/test.ejs.t
  bun.lockb
  package.json
Labels: priority high
