Repository Kyutech-C3/ToyBox_front_replace, pull requests merged in 2023-11, with the labels that each got.

#43 Feat/skeleton UI #31
  src/components/ui/Skeleton/index.stories.tsx
  src/components/ui/Skeleton/index.test.tsx
  src/components/ui/Skeleton/index.tsx
  tailwind.config.js
Labels: priority medium

#45 Feat/tag UI #13
  src/components/ui/Tag/index.stories.tsx
  src/components/ui/Tag/index.test.tsx
  src/components/ui/Tag/index.tsx
Labels: priority medium

#46 docs: add pull request template markdown
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority low

#48 Feat/date label UI #16
  package.json
  pnpm-lock.yaml
  src/components/ui/DateLabel/index.stories.tsx
  src/components/ui/DateLabel/index.test.tsx
  src/components/ui/DateLabel/index.tsx
  src/libs/dateFormat/index.test.ts
  src/libs/dateFormat/index.ts
Labels: priority medium

#57 Feaet/typography UI #14
  src/components/ui/Typography/index.stories.tsx
  src/components/ui/Typography/index.test.tsx
  src/components/ui/Typography/index.tsx
Labels: priority medium

#56 Feat/full screen #28
  package.json
  pnpm-lock.yaml
  src/components/functional/FullScreen/hook.ts
  src/components/functional/FullScreen/index.stories.tsx
  src/components/functional/FullScreen/index.test.tsx
  src/components/functional/FullScreen/index.tsx
Labels: priority low

#59 Chore/dependabot config #58
  .github/dependabot.yml
  .github/workflows/auto_merge.yml
Labels: priority medium

#63 chore: chromatic deploy work only not dependent PR
  .github/workflows/chromatic_deploy.yml
Labels: priority medium

#66 chore: add eslint rule of React import
  .eslintrc.json
  src/components/ui/Tag/index.tsx
Labels: priority low

#64 feat: add avatar ui component
  package.json
  pnpm-lock.yaml
  src/components/ui/Avatar/index.stories.tsx
  src/components/ui/Avatar/index.test.tsx
  src/components/ui/Avatar/index.tsx
Labels: priority medium

#69 fix: workflow bug fix
  .github/workflows/auto_merge.yml
  .github/workflows/chromatic_deploy.yml
Labels: priority high

#75 Feat/eslint rules #70
  .eslintrc.json
  src/components/ui/Tag/index.tsx
  src/libs/utils.ts
Labels: priority medium

#67 Feat/tooltip UI #18
  package.json
  pnpm-lock.yaml
  src/components/ui/Tooltip/index.stories.tsx
  src/components/ui/Tooltip/index.test.tsx
  src/components/ui/Tooltip/index.tsx
Labels: priority medium

#89 feat: add accordion ui
  package.json
  pnpm-lock.yaml
  src/components/ui/Accordion/index.stories.tsx
  src/components/ui/Accordion/index.test.tsx
  src/components/ui/Accordion/index.tsx
Labels: priority medium

#72 feat: add icon button ui
  src/components/ui/Button/index.stories.tsx
  src/components/ui/Button/index.tsx
  src/components/ui/IconButton/index.stories.tsx
  src/components/ui/IconButton/index.test.tsx
  src/components/ui/IconButton/index.tsx
Labels: priority medium

#86 feat: add popover ui
  package.json
  pnpm-lock.yaml
  src/components/ui/Popover/index.stories.tsx
  src/components/ui/Popover/index.test.tsx
  src/components/ui/Popover/index.tsx
Labels: priority medium

#97 feat: date diff label ui
  src/components/ui/DateDiffLabel/constant.ts
  src/components/ui/DateDiffLabel/index.stories.tsx
  src/components/ui/DateDiffLabel/index.test.tsx
  src/components/ui/DateDiffLabel/index.tsx
  src/components/ui/DateDiffLabel/logic.ts
Labels: priority medium, ui

#96 Feat/image crop #87
  cspell.config.json
  package.json
  pnpm-lock.yaml
  src/components/model/ImageCrop/hooks/index.ts
  src/components/model/ImageCrop/index.stories.tsx
  src/components/model/ImageCrop/index.test.tsx
  src/components/model/ImageCrop/index.tsx
  src/components/model/ImageCrop/logic/getCroppedImgBase64.ts
  src/components/model/ImageCrop/presentations/error.tsx
  src/components/model/ImageCrop/presentations/index.tsx
  src/components/model/ImageCrop/presentations/loading.tsx
  src/libs/ErrorBoundary/index.tsx
  src/libs/ImageCrop/index.ts
Labels: priority medium

#98 feat: add custom color
  tailwind.config.js
Labels: priority medium

#95 feat: add modal (dialog) ui ( #84 )
  package.json
  pnpm-lock.yaml
  src/components/ui/Dialog/index.stories.tsx
  src/components/ui/Dialog/index.test.tsx
  src/components/ui/Dialog/index.tsx
Labels: priority medium

#105 feat: add pagination model ( #104 )
  src/components/ui/Pagination/index.stories.tsx
  src/components/ui/Pagination/index.test.tsx
  src/components/ui/Pagination/index.tsx
  src/components/ui/Pagination/items/Dots.tsx
  src/components/ui/Pagination/items/PageButton.tsx
  src/components/ui/Pagination/logic/CheckElementRequired.ts
  src/components/ui/Pagination/logic/restrictRange.ts
Labels: priority medium
